#!/bin/bash

# Script for testing producer-consumer program (C++ version 2)
#

make prime-par1 > /dev/null 2>&1
make prime-par2 > /dev/null 2>&1
make prime-par3 > /dev/null 2>&1

for i in 10 100 1000 1000 10000 100000
do  
    for j in 1 2 4 8 16 32 64 128
    do  echo "---------------------------"   
        echo ./prime-par1 $i $j
        ./prime-par1 $i $j
    done
done

for i in 10 100 1000 1000 10000 100000
do   
    for j in 1 2 4 8 16 32 64 128
    do  echo "---------------------------"   
        echo ./prime-par2 $i $j
        ./prime-par2 $i $j
    done
done


for i in 10 100 1000 1000 10000 100000
do  
    for j in 1 2 4 8 16 32 64 128
    do  echo "---------------------------"   
        echo ./prime-par3 $i $j
        ./prime-par3 $i $j
    done
done

exit 0
