#!/bin/bash

# Script for testing producer-consumer program (C++ version 2)
#

make prime-par1
make prime-par2
make prime-par3

# echo $pwd   
# echo "---------------------------"   
# echo ./prime-par1
./prime-par1

for i in 10 100 1000 1000 10000 1000000
do  #echo "---------------------------"   
    for j in 1 2 4 8 16 32 64 128
    do  #echo "---------------------------"   
        #echo ./prime-par1 $i $j
        ./prime-par1 $i $j
    done
done

# echo $pwd   
# echo "---------------------------"   
# echo ./prime-par2
./prime-par2

for i in 10 100 1000 1000 10000 1000000
do  #echo "---------------------------"   
    for j in 1 2 4 8 16 32 64 128
    do  #echo "---------------------------"   
       # echo ./prime-par2 $i $j
        ./prime-par2 $i $j
    done
done

# echo $pwd   
# echo "---------------------------"   
# echo ./prime-par3
./prime-par3

for i in 10 100 1000 1000 10000 1000000
do  #echo "---------------------------"   
    for j in 1 2 4 8 16 32 64 128
    do  #echo "---------------------------"   
        #echo ./prime-par3 $i $j
        ./prime-par3 $i $j
    done
done

exit 0
